entrypoint: "rm -rf tmp/pids/server.pid && bundle exec rails s --port $PORT -b '0.0.0.0'"
env: standard
runtime: ruby32

env_variables:
  SECRET_KEY_BASE: [SECRET_KEY]
  SECRET_TOKEN: [SECRET_TOKEN]

beta_settings:
  cloud_sql_instances: albertmw-pg-cloud
